### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by darrylmendo** [salszu/portfolio#1]
@salszu, nice job with your site. Seems like you have the grid system down. Were you going for that staggered effect? I would recommend changing your indentation settings in sublime to 2 spaces. You can see the difference is dramatic between your navbar code from bootstrap with your code for the content of your page. We will soon be writing html files that will go 400 lines easily. You will be nesting within nesting and so on (inception style). Having 2 space indentation will be a life saver. Look into changing settings in sublime or one of us can help you out with it. Also, make your social network links open in a new tab. this way the user never actually leaves your site. Typically that's what you want to do. The last thing is why do you have the bootstrap cdn link tag twice? Plus you also have a bootswatch cdn. If you're using bootswatch you don't need to use the bootstrap cdn at all. Bootswatch has all the styles for bootstrap just with a different variation. Other than that great job! Keep it up.

**Comment by salszu** [comment]
@darrylmendo,  I did want that staggered offset look for bigger screens, I was hoping it would look better than it does but maybe once there's actual content there it'll feel more full. 

I'll make sure to check out the indent settings in sublime, just last night I installed that package control project manager for sublime to pull the "prettify" plugin Christian was using during the demos, I know its the easy way out but it'll at least help clean up my old code. 

I wasn't certain about the bootswatch/bootstrap CDN's  but i'll keep that in mind for future work. 

Thanks for your input.
